development:
  :email_config:
    :address: smtp.gmail.com
    :port: 587
    :email_domain: mwscotts.com
    :user_name: dummy@mwscotts.com
    :password: dummy1mw
    :authentication: login
    :host: localhost:3000
    :office_address: ed@mwscotts.com
    :pastor_address: ed@mwscotts.com
    :webmaster_address: webmaster@sfxmw.com

test:
  email_config:
    address: smtp.yourserver.com
    port: 25
    user_name: username
    password: password

production:
  email_config:
    :address: smtp.gmail.com
    :port: 587
    :email_domain: mwscotts.com
    :user_name: dummy@mwscotts.com
    :password: dummy1mw
    :authentication: login
    :host: localhost:3000
    :office_address: nancy.almony@sfxmw.com
    :pastor_address: fr.paul.beach@sfxmw.com
    :webmaster_address: webmaster@sfxmw.com


    